### ISSUE TITLE
Add tutorials for torrent uploads using different BitTorrent clients

### ISSUE THREAD

**Issue by josecelano** [josecelano/torrust-index-gui-user-guide#1]
Relates to: https://github.com/torrust/torrust-index-gui/discussions/538

- [ ] https://github.com/torrust/torrust-index-gui-user-guide/issues/2
- [ ] https://github.com/torrust/torrust-index-gui-user-guide/issues/3
- [ ] https://github.com/torrust/torrust-index-gui-user-guide/issues/4
- [ ] https://github.com/torrust/torrust-index-gui-user-guide/issues/5
- [ ] https://github.com/torrust/torrust-index-gui-user-guide/issues/6
